site:
  title: Systemdokumentasjon for Team Pensjonsbrev
  url: https://navikt.github.io/pensjonsbrev/
  start_page: docs::index.adoc

content:
  sources:
    - url: ..
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://github.com/navikt/pensjon-docs-ui/releases/download/2025.01.15-11.05-2ec57f1f221e/ui-bundle.zip
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: false
  supplemental_files: supplemental_ui

output:
  dir: ./build/site

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    lang: nb-NO
    last-update-label: 'Sist oppdatert:'
    icons: font
    kroki-fetch-diagram: true

antora:
  extensions:
    - '@antora/lunr-extension'