name: .verify-frontend.yaml

on:
  workflow_call:
    inputs:
      workingDir:
        description: 'Working directory'
        required: true
        type: string
      cypress:
        description: 'Run cypress tests'
        required: true
        type: boolean

jobs:
  verify-bff:
    name: Verify bff tests, lint and typescript errors
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
      - name: Install bff dependencies
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run ESLint
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm run lint

      - name: Check for typescript errors
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm run check-types

      - name: Build bff
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm run build

  verify-frontend:
    name: Verify frontend tests, lint and typescript errors
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.workingDir }}/frontend
      - name: Install dependencies
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm ci

      - name: Cypress run e2e tests
        if: ${{ inputs.cypress }}
        uses: cypress-io/github-action@e65cba2e7319696fc0fdc4d5a319b737aec4ba1c
        with:
          working-directory: ${{ inputs.workingDir }}/frontend
          install: false
          browser: chrome
          component: false
          start: npm run dev

      - name: Cypress run component tests
        if: ${{ inputs.cypress }}
        uses: cypress-io/github-action@e65cba2e7319696fc0fdc4d5a319b737aec4ba1c
        with:
          working-directory: ${{ inputs.workingDir }}/frontend
          install: false
          browser: chrome
          component: true

      - name: Run tests
        if: ${{ inputs.cypress }}
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run test

      - name: Run ESLint
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run lint

      - name: Run stylelint
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run stylelint

      - name: Check for typescript errors
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run check-types

      - name: Upload failed Cypress screenshots
        uses: actions/upload-artifact@v5
        if: ${{ failure() && inputs.cypress}}
        with:
          name: cypress-screenshots
          path: ${{ inputs.workingDir }}/frontend/cypress/screenshots